clear('avoidObstaclesControllerInstance');
avoidObstaclesControllerInstance = avoid_obstacles.src.AvoidObstaclesController;
avoidObstaclesControllerInstance.subscribeToTopics;
avoidObstaclesControllerInstance.createPublishers;
avoidObstaclesControllerInstance.runNode;